-- PostgreSQL 15+ schema matching the current SQLite application contract.
CREATE TABLE IF NOT EXISTS projects (id text PRIMARY KEY, name text NOT NULL, timezone text NOT NULL, active_snapshot_id text NOT NULL, seed_version text NOT NULL);
CREATE TABLE IF NOT EXISTS users (id text PRIMARY KEY, full_name text NOT NULL, email text UNIQUE, password_hash text, active boolean NOT NULL DEFAULT true, created_at timestamptz, updated_at timestamptz);
CREATE TABLE IF NOT EXISTS memberships (project_id text NOT NULL REFERENCES projects(id), user_id text NOT NULL REFERENCES users(id), role text NOT NULL, active boolean NOT NULL DEFAULT true, reporting_scope text, discipline text, area text, created_at timestamptz, updated_at timestamptz, PRIMARY KEY(project_id,user_id));
CREATE TABLE IF NOT EXISTS schedule_snapshots (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), imported_at timestamptz NOT NULL, source_hash text NOT NULL);
CREATE TABLE IF NOT EXISTS activities (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), snapshot_id text NOT NULL REFERENCES schedule_snapshots(id), wbs text NOT NULL, level smallint NOT NULL CHECK(level IN (5,6)), name text NOT NULL, discipline text NOT NULL, work_type text NOT NULL, asset_id text NOT NULL, location_json jsonb NOT NULL, planned_start date NOT NULL, planned_finish date NOT NULL, planned_quantity_json jsonb, actual_progress_percent numeric(5,2) NOT NULL CHECK(actual_progress_percent BETWEEN 0 AND 100), actual_quantity_json jsonb, actual_as_of timestamptz, source_verification_id text, version integer NOT NULL DEFAULT 1, UNIQUE(snapshot_id,wbs));
CREATE TABLE IF NOT EXISTS execution_events (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), reporter_id text NOT NULL REFERENCES users(id), observed_at timestamptz NOT NULL, received_at timestamptz NOT NULL, evidence_json jsonb NOT NULL, extracted_facts_json jsonb NOT NULL, status text NOT NULL CHECK(status IN ('submitted','proposed','verified','rejected')), version integer NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS match_proposals (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), execution_event_id text NOT NULL UNIQUE REFERENCES execution_events(id), snapshot_id text NOT NULL REFERENCES schedule_snapshots(id), engine_version text NOT NULL, config_version text NOT NULL, mode text NOT NULL CHECK(mode IN ('primary','deterministic_fallback')), status text NOT NULL CHECK(status IN ('proposed','verified','rejected')), candidates_json jsonb NOT NULL, created_at timestamptz NOT NULL, version integer NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS verifications (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), proposal_id text NOT NULL UNIQUE REFERENCES match_proposals(id), activity_id text, planner_id text NOT NULL REFERENCES users(id), decision text NOT NULL CHECK(decision IN ('verified','rejected')), progress_percent numeric(5,2), actual_quantity_json jsonb, note text, created_at timestamptz NOT NULL);
CREATE TABLE IF NOT EXISTS idempotency_records (project_id text NOT NULL, actor_id text NOT NULL, route text NOT NULL, key text NOT NULL, request_hash text NOT NULL, response_json jsonb NOT NULL, response_status integer NOT NULL, created_at timestamptz NOT NULL, PRIMARY KEY(project_id,actor_id,route,key));
CREATE TABLE IF NOT EXISTS audit_entries (project_id text NOT NULL, sequence bigint NOT NULL, previous_hash text NOT NULL, entry_hash text NOT NULL, canonical_payload jsonb NOT NULL, actor_id text NOT NULL, action text NOT NULL, entity_type text NOT NULL, entity_id text NOT NULL, occurred_at timestamptz NOT NULL, request_id text NOT NULL, PRIMARY KEY(project_id,sequence), UNIQUE(project_id,entry_hash));
CREATE TABLE IF NOT EXISTS outbox_events (id text PRIMARY KEY, project_id text NOT NULL, aggregate_type text NOT NULL, aggregate_id text NOT NULL, type text NOT NULL, payload_json jsonb NOT NULL, occurred_at timestamptz NOT NULL, published_at timestamptz);

CREATE INDEX IF NOT EXISTS idx_activities_project_snapshot ON activities(project_id,snapshot_id);
CREATE INDEX IF NOT EXISTS idx_events_project_status ON execution_events(project_id,status);
CREATE INDEX IF NOT EXISTS idx_proposals_project_status ON match_proposals(project_id,status);
CREATE INDEX IF NOT EXISTS idx_audit_project_sequence ON audit_entries(project_id,sequence);
CREATE INDEX IF NOT EXISTS idx_outbox_unpublished ON outbox_events(published_at) WHERE published_at IS NULL;
