-- PostgreSQL 15+ production schema. JSON payloads are JSONB; command transactions
-- lock proposal/activity rows with SELECT ... FOR UPDATE in the repository adapter.
CREATE TABLE projects (id text PRIMARY KEY, name text NOT NULL, timezone text NOT NULL, active_snapshot_id text NOT NULL, seed_version text NOT NULL);
CREATE TABLE users (id text PRIMARY KEY, name text NOT NULL);
CREATE TABLE memberships (project_id text REFERENCES projects(id), user_id text REFERENCES users(id), role text NOT NULL CHECK (role IN ('supervisor','planner','viewer','admin')), PRIMARY KEY(project_id,user_id));
CREATE TABLE schedule_snapshots (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), imported_at timestamptz NOT NULL, source_hash text NOT NULL);
CREATE TABLE activities (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), snapshot_id text NOT NULL REFERENCES schedule_snapshots(id), wbs text NOT NULL, level smallint NOT NULL CHECK(level IN (5,6)), name text NOT NULL, discipline text NOT NULL, work_type text NOT NULL, asset_id text NOT NULL, location_json jsonb NOT NULL, planned_start date NOT NULL, planned_finish date NOT NULL, planned_quantity_json jsonb, actual_progress_percent numeric(5,2) NOT NULL CHECK(actual_progress_percent BETWEEN 0 AND 100), actual_quantity_json jsonb, actual_as_of timestamptz, source_verification_id text, version integer NOT NULL DEFAULT 1, UNIQUE(snapshot_id,wbs));
CREATE TABLE execution_events (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), reporter_id text NOT NULL REFERENCES users(id), observed_at timestamptz NOT NULL, received_at timestamptz NOT NULL, evidence_json jsonb NOT NULL, extracted_facts_json jsonb NOT NULL, status text NOT NULL CHECK(status IN ('submitted','proposed','verified','rejected')), version integer NOT NULL DEFAULT 1);
CREATE TABLE match_proposals (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), execution_event_id text NOT NULL UNIQUE REFERENCES execution_events(id), snapshot_id text NOT NULL REFERENCES schedule_snapshots(id), engine_version text NOT NULL, config_version text NOT NULL, mode text NOT NULL CHECK(mode IN ('primary','deterministic_fallback')), status text NOT NULL CHECK(status IN ('proposed','verified','rejected')), candidates_json jsonb NOT NULL, created_at timestamptz NOT NULL, version integer NOT NULL DEFAULT 1);
CREATE TABLE verifications (id text PRIMARY KEY, project_id text NOT NULL REFERENCES projects(id), proposal_id text NOT NULL UNIQUE REFERENCES match_proposals(id), activity_id text, planner_id text NOT NULL REFERENCES users(id), decision text NOT NULL CHECK(decision IN ('verified','rejected')), progress_percent numeric(5,2), actual_quantity_json jsonb, note text, created_at timestamptz NOT NULL);
CREATE TABLE idempotency_records (project_id text NOT NULL, actor_id text NOT NULL, route text NOT NULL, key text NOT NULL, request_hash text NOT NULL, response_json jsonb NOT NULL, response_status integer NOT NULL, created_at timestamptz NOT NULL, PRIMARY KEY(project_id,actor_id,route,key));
CREATE TABLE audit_entries (project_id text NOT NULL, sequence bigint NOT NULL, previous_hash text NOT NULL, entry_hash text NOT NULL, canonical_payload jsonb NOT NULL, actor_id text NOT NULL, action text NOT NULL, entity_type text NOT NULL, entity_id text NOT NULL, occurred_at timestamptz NOT NULL, request_id text NOT NULL, PRIMARY KEY(project_id,sequence), UNIQUE(project_id,entry_hash));
CREATE TABLE outbox_events (id text PRIMARY KEY, project_id text NOT NULL, aggregate_type text NOT NULL, aggregate_id text NOT NULL, type text NOT NULL, payload_json jsonb NOT NULL, occurred_at timestamptz NOT NULL, published_at timestamptz);
