/**
 * ExecLink canonical JSON and hash primitives — NORMATIVE REFERENCE.
 *
 * This file is the executable form of the "Canonicalization and hashing" section
 * of docs/ARCHITECTURE.md. services/api (Python), apps/web (TypeScript) and
 * apps/field (Dart) each implement the prose spec; all three are checked against
 * data/spec/canonicalization-vectors.json, which is generated by this reference.
 *
 * If a change here changes a digest, it is a BREAKING change: bump `specVersion`
 * and every stored chain must be migrated or invalidated. Never silently change
 * canonical output — a stored audit chain that no longer recomputes is, for
 * verification purposes, a tampered chain.
 *
 * specVersion: canonical-json-v1
 */

import { createHash } from "node:crypto";

export const CANONICAL_SPEC_VERSION = "canonical-json-v1";

/** previousHash of the first entry in a chain. 64 lowercase hex zeros. */
export const GENESIS_HASH = "0".repeat(64);

export type JsonValue =
  | null
  | boolean
  | number
  | string
  | JsonValue[]
  | { [key: string]: JsonValue };

/* ------------------------------------------------------------------ *
 * Numbers
 * ------------------------------------------------------------------ */

/**
 * Format a number the way every ExecLink implementation must.
 *
 * The rule is "shortest round-trip decimal", with three normalizations that are not
 * cosmetic. Each one has been observed to diverge between languages:
 *
 * 1. An integral value NEVER carries a decimal point. JSON.parse("45.0") yields the
 *    double 45 in JavaScript and Dart but the float 45.0 in Python, and the default
 *    string conversions disagree ("45" vs "45.0"). Without this the same
 *    idempotency body hashes differently in services/api than in apps/field, which
 *    surfaces as a spurious 409 IDEMPOTENCY_CONFLICT on a legitimate retry.
 * 2. Negative zero normalizes to "0". It compares equal to 0 but would otherwise
 *    hash differently.
 * 3. The exponent has NO leading zeros and NO "+" sign. Python's repr(1e-07)
 *    yields "1e-07" while JavaScript's String(1e-7) yields "1e-7"; the two differ
 *    only in that padding, and the padding is enough to change the digest.
 *
 * Exponent form is used only outside 1e-6 <= |x| < 1e21, matching ECMAScript
 * Number::toString, so the common cases stay in plain decimal.
 */
export function canonicalNumber(value: number): string {
  if (!Number.isFinite(value)) {
    throw new TypeError(`canonical JSON cannot encode non-finite number: ${String(value)}`);
  }
  if (value === 0) return "0";
  if (Number.isInteger(value) && Math.abs(value) < 1e21) {
    return String(value);
  }
  return String(value).replace(/e([+-])?0*(\d+)$/, (_match, sign, digits) => {
    return `e${sign === "-" ? "-" : ""}${digits}`;
  });
}

/* ------------------------------------------------------------------ *
 * Strings
 * ------------------------------------------------------------------ */

const ESCAPES: Record<string, string> = {
  '"': '\\"',
  "\\": "\\\\",
  "\b": "\\b",
  "\f": "\\f",
  "\n": "\\n",
  "\r": "\\r",
  "\t": "\\t"
};

/**
 * Escape per RFC 8259 with the short forms for the five characters that have them,
 * \u00XX for the remaining C0 controls, and literal UTF-8 for everything else.
 * Non-ASCII is NOT escaped to \uXXXX: the digest is taken over UTF-8 bytes, and
 * escaping would make it depend on the writer's choice of \u form.
 */
export function canonicalString(value: string): string {
  let out = '"';
  for (const char of value) {
    const escape = ESCAPES[char];
    if (escape !== undefined) {
      out += escape;
    } else if (char < " ") {
      out += `\\u${char.codePointAt(0)!.toString(16).padStart(4, "0")}`;
    } else {
      out += char;
    }
  }
  return `${out}"`;
}

/* ------------------------------------------------------------------ *
 * Objects and arrays
 * ------------------------------------------------------------------ */

/**
 * Sort object keys ascending by Unicode code point, which is byte-for-byte the
 * same order as sorting the UTF-8 encoding of the keys. This is the ordering used
 * by RFC 8785 (JCS) for the ASCII key space, and it is the ordering Python's
 * sorted(), Dart's compareTo and JavaScript's default sort all agree on for the
 * ASCII keys ExecLink uses.
 */
function sortedKeys(value: { [key: string]: JsonValue }): string[] {
  return Object.keys(value).sort((a, b) => (a < b ? -1 : a > b ? 1 : 0));
}

export function canonicalJson(value: JsonValue): string {
  if (value === null) return "null";
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number") return canonicalNumber(value);
  if (typeof value === "string") return canonicalString(value);
  if (Array.isArray(value)) {
    return `[${value.map((item) => canonicalJson(item)).join(",")}]`;
  }
  if (typeof value === "object") {
    const record = value as { [key: string]: JsonValue | undefined };
    const body = sortedKeys(record as { [key: string]: JsonValue })
      .map((key) => {
        const member = record[key];
        if (member === undefined) {
          // Only reachable when a caller built the object in code rather than
          // parsing JSON, since JSON has no undefined. Throwing is deliberate:
          // silently dropping the member would hash a different object from the
          // one the caller believes it hashed, and the digest would still verify.
          throw new TypeError(
            `canonical JSON cannot encode an undefined member at key "${key}"; ` +
              "omit the key instead of setting it to undefined"
          );
        }
        return `${canonicalString(key)}:${canonicalJson(member)}`;
      })
      .join(",");
    return `{${body}}`;
  }
  throw new TypeError(`canonical JSON cannot encode ${typeof value}`);
}

/* ------------------------------------------------------------------ *
 * Digests
 * ------------------------------------------------------------------ */

/**
 * Hex-encoded SHA-256 over the UTF-8 bytes of a canonical JSON string.
 * Lowercase hex, 64 characters, no prefix.
 *
 * Hashing is a server-side concern: services/api writes the chain and QA verifies
 * it, so this module's digest helpers are Node-only by design and are not part of
 * the browser-safe entry point ("./canonical-json" exports only canonicalJson).
 */
export function sha256Hex(input: string): string {
  return createHash("sha256").update(input, "utf8").digest("hex");
}

/* ------------------------------------------------------------------ *
 * Audit chain
 * ------------------------------------------------------------------ */

/**
 * The exact member set of an audit entry body, in the sense that the digest is
 * taken over these fields and nothing else. Adding a field changes every digest
 * in the chain, so new fields must arrive with a specVersion bump.
 */
export interface AuditEntryBody {
  sequence: number;
  projectId: string;
  occurredAt: string;
  actorId: string;
  actorRole: string;
  action: string;
  entityType: string;
  entityId: string;
  requestId: string;
  payload: JsonValue;
  previousHash: string;
}

export function auditEntryBody(entry: AuditEntryBody): JsonValue {
  return {
    sequence: entry.sequence,
    projectId: entry.projectId,
    occurredAt: entry.occurredAt,
    actorId: entry.actorId,
    actorRole: entry.actorRole,
    action: entry.action,
    entityType: entry.entityType,
    entityId: entry.entityId,
    requestId: entry.requestId,
    payload: entry.payload,
    previousHash: entry.previousHash
  };
}

/**
 * entry_hash = SHA-256(utf8(canonicalJson(entry_body)))
 *
 * previousHash is INSIDE the hashed body. Hashing the body without the link would
 * let an attacker rewrite an entry's predecessor undetected, which defeats the
 * chain.
 */
export function auditEntryHash(entry: AuditEntryBody): string {
  return sha256Hex(canonicalJson(auditEntryBody(entry)));
}

export interface ChainVerification {
  valid: boolean;
  checked: number;
  /** 1-based sequence of the first entry that failed, or null when valid. */
  brokenAtSequence: number | null;
  reason: string | null;
}

/**
 * A persisted row: the hashed body plus the digest that was stored alongside it.
 * The two are kept as separate members so the digest can never be folded into the
 * body it authenticates.
 */
export interface StoredAuditEntry extends AuditEntryBody {
  entryHash: string;
}

export interface ChainVerification {
  valid: boolean;
  checked: number;
  /** 1-based sequence of the first entry that failed, or null when valid. */
  brokenAtSequence: number | null;
  reason: string | null;
}

/**
 * Verify a chain from PERSISTED rows — never from an in-process copy, which would
 * only prove the writer was internally consistent rather than that the stored
 * history is intact.
 *
 * Requires: sequence contiguous from 1, previousHash equal to the prior row's
 * entryHash (or GENESIS_HASH at sequence 1), and every stored entryHash equal to
 * the digest recomputed from that row's body. The link check and the digest check
 * are independent on purpose: the link check alone is defeated by rewriting an
 * entire suffix of the chain, and the digest check alone is defeated by a forged
 * standalone entry.
 */
export function verifyAuditChain(rows: readonly StoredAuditEntry[]): ChainVerification {
  const ordered = [...rows].sort((a, b) => a.sequence - b.sequence);
  let previous = GENESIS_HASH;
  for (let index = 0; index < ordered.length; index += 1) {
    const entry = ordered[index] as StoredAuditEntry;
    const fail = (reason: string): ChainVerification => ({
      valid: false,
      checked: index,
      brokenAtSequence: entry.sequence,
      reason
    });
    if (entry.sequence !== index + 1) {
      return fail(`sequence gap or duplicate: expected ${index + 1}, found ${entry.sequence}`);
    }
    if (entry.previousHash !== previous) {
      return fail("previous_hash does not match the preceding entry_hash");
    }
    if (auditEntryHash(entry) !== entry.entryHash) {
      return fail("entry_hash does not match the recomputed digest of the entry body");
    }
    previous = entry.entryHash;
  }
  return { valid: true, checked: ordered.length, brokenAtSequence: null, reason: null };
}

/* ------------------------------------------------------------------ *
 * Idempotency
 * ------------------------------------------------------------------ */

export interface IdempotencyFingerprint {
  method: string;
  /** Fully-resolved path with real IDs substituted, e.g. /projects/PRJ-1/x/verify. */
  path: string;
  /** Parsed request body. Absent body is the empty object, never null-vs-{} ambiguity. */
  body: JsonValue;
}

/**
 * request_hash = SHA-256(utf8(canonicalJson({ method, path, body })))
 *
 * The path is resolved, not templated: the same idempotency key replayed against a
 * different resource is a different command and must not return the first
 * resource's response.
 */
export function idempotencyRequestHash(input: IdempotencyFingerprint): string {
  return sha256Hex(
    canonicalJson({ method: input.method.toUpperCase(), path: input.path, body: input.body ?? {} })
  );
}
