"use client";

import { useState } from "react";
import { Button, ConfidenceBadge, Dialog, DisciplineBadge, Drawer, EmptyState, ErrorState, FilterBar, PageHeader, PopoverExample, SearchInput, SectionHeader, Skeleton, StatusBadge, Tooltip } from "@/components/ui/design-system";
import { Icon } from "@/components/ui/icons";

export default function DesignSystemPage() {
  const [drawer, setDrawer] = useState(false);
  const [modal, setModal] = useState(false);
  return <main className="showcase">
    <div className="showcase-banner"><a href="/">← Return to Control Center</a><span>DEVELOPMENT ONLY · DESIGN SYSTEM</span></div>
    <PageHeader eyebrow="FOUNDATION / TASK 00" title="ExecLink interface system" description="Reusable patterns for dense, trustworthy project-controls workflows." actions={<><Button variant="secondary" onClick={() => setModal(true)}>Open modal</Button><Button variant="primary" onClick={() => setDrawer(true)}>View activity detail</Button></>}/>

    <section className="showcase-section"><SectionHeader title="Typography & hierarchy" description="A compact type scale designed for operational scanning."/><div className="type-specimen"><div><span>PAGE TITLE · 26 / 32</span><h1>Verification Center</h1></div><div><span>SECTION · 17 / 24</span><h2>Events requiring review</h2></div><div><span>BODY · 14 / 21</span><p>Human verification remains the trust boundary before actual progress changes.</p></div><div><span>METADATA · 12 / 16</span><small>DATA DATE · 25 SEP 2026</small></div></div></section>

    <div className="showcase-grid"><section className="showcase-section"><SectionHeader title="Actions & inputs"/><div className="component-row"><Button variant="primary">Verify progress</Button><Button variant="secondary">Review evidence</Button><Button variant="ghost">Dismiss</Button><Button variant="danger">Reject proposal</Button></div><div className="input-grid"><label className="ds-field"><span>Activity owner</span><input defaultValue="North River Civil JV"/></label><SearchInput placeholder="Search activities, assets, evidence…"/><label className="ds-field"><span>Discipline</span><select defaultValue="Civil"><option>Civil</option><option>Piping</option><option>Electrical</option></select></label></div></section>
      <section className="showcase-section"><SectionHeader title="Operational states"/><div className="badge-grid"><StatusBadge tone="success">Verified</StatusBadge><StatusBadge tone="warning">Review</StatusBadge><StatusBadge>Unmatched</StatusBadge><StatusBadge tone="danger">Blocked</StatusBadge><StatusBadge tone="info">In Progress</StatusBadge><StatusBadge tone="success">Completed</StatusBadge></div><div className="badge-grid"><DisciplineBadge>Civil</DisciplineBadge><DisciplineBadge>Piping</DisciplineBadge><DisciplineBadge>Electrical</DisciplineBadge><DisciplineBadge>Instrumentation</DisciplineBadge></div><div className="confidence-row"><ConfidenceBadge value={96}/><ConfidenceBadge value={78}/><ConfidenceBadge value={42}/></div></section></div>

    <section className="showcase-section"><SectionHeader title="Filters & dense table" description="Rows preserve context while keeping review actions close to the evidence." action={<PopoverExample/>}/><FilterBar resultCount="24 activities"><button className="filter-chip active">All events</button><button className="filter-chip">Needs review</button><button className="filter-chip">Critical path</button><select aria-label="Filter by discipline"><option>All disciplines</option><option>Civil</option></select></FilterBar><div className="ds-table-wrap"><table className="ds-table"><thead><tr><th>Activity</th><th>Discipline</th><th>Status</th><th>Confidence</th><th>Data date</th><th><span className="sr-only">Actions</span></th></tr></thead><tbody><tr><td><strong>Pier P12 reinforcement fixing</strong><small>ACT-1.2.1 · WBS 1.2.1</small></td><td><DisciplineBadge>Civil</DisciplineBadge></td><td><StatusBadge tone="warning">Review</StatusBadge></td><td><ConfidenceBadge value={78}/></td><td>25 Sep 2026</td><td><Button variant="ghost" onClick={() => setDrawer(true)}>Open</Button></td></tr><tr><td><strong>Cooling water line pressure test</strong><small>ACT-3.4.8 · WBS 3.4.8</small></td><td><DisciplineBadge>Piping</DisciplineBadge></td><td><StatusBadge tone="success">Verified</StatusBadge></td><td><ConfidenceBadge value={96}/></td><td>25 Sep 2026</td><td><Button variant="ghost">Open</Button></td></tr><tr><td><strong>Substation cable tray installation</strong><small>ACT-6.2.4 · WBS 6.2.4</small></td><td><DisciplineBadge>Electrical</DisciplineBadge></td><td><StatusBadge tone="danger">Blocked</StatusBadge></td><td><ConfidenceBadge value={42}/></td><td>24 Sep 2026</td><td><Button variant="ghost">Open</Button></td></tr></tbody></table></div></section>

    <div className="showcase-grid showcase-grid--states"><section className="showcase-section"><SectionHeader title="Empty state"/><EmptyState/></section><section className="showcase-section"><SectionHeader title="Error state"/><ErrorState/></section><section className="showcase-section"><SectionHeader title="Loading state"/><Skeleton/></section></div>
    <section className="showcase-section"><SectionHeader title="Context surfaces"/><div className="component-row"><Tooltip label="Evidence is retained in the audit trail"><button className="ds-icon-button" aria-label="Evidence information"><Icon name="help"/></button></Tooltip><PopoverExample/><Button variant="secondary" onClick={() => setModal(true)}>Open confirmation</Button><Button variant="secondary" onClick={() => setDrawer(true)}>Open detail drawer</Button></div></section>
    <Drawer open={drawer} onClose={() => setDrawer(false)}/><Dialog open={modal} title="Confirm verified progress" onClose={() => setModal(false)}><p>This will update ACT-1.2.1 to 45% and create an immutable audit record.</p><div className="ds-dialog-actions"><Button variant="ghost" onClick={() => setModal(false)}>Cancel</Button><Button variant="primary" onClick={() => setModal(false)}>Confirm verification</Button></div></Dialog>
  </main>;
}
