import { ArrowUpRight, ChevronDown, Filter, Info } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Button, ConfidenceBadge, DisciplineBadge, DrawerDemo, EmptyState, ErrorState, InsetModule, MajorPanel, ModalDemo, PanelHeader, PopoverDemo, SearchInput, SectionHeader, SkeletonState, StatusBadge, Surface } from "@/components/ui";

const brandColors = [
  ["Primary Blue", "#2563EB"], ["Deep Blue", "#172554"], ["Information", "#3B82F6"],
  ["Application", "#F6F8FB"], ["Surface", "#FFFFFF"], ["Border", "#E2E8F0"], ["Text", "#0F172A"],
];
const semanticColors = [
  ["Verified", "#16804C"], ["Review", "#A16207"], ["Critical", "#B42318"], ["Neutral", "#64748B"],
];
const statuses = ["Verified", "Auto-suggest", "Review", "Unmatched", "Rejected", "Blocked", "Completed", "In Progress"];
const disciplines = ["Civil", "Structural", "Piping", "Static Equipment", "Rotating Equipment", "Electrical", "Instrumentation", "HSE"];
const activities = [
  { id: "ACT-C240", name: "Foundation concrete pour — Area B", discipline: "Civil", progress: 100, confidence: 96, status: "Verified" },
  { id: "ACT-P110", name: "P-110 erection and alignment", discipline: "Piping", progress: 78, confidence: 92, status: "In Progress" },
  { id: "ACT-E315", name: "MCC-02 cable termination", discipline: "Electrical", progress: 42, confidence: 78, status: "Review" },
  { id: "ACT-I085", name: "Loop check — Compressor Train 1", discipline: "Instrumentation", progress: 0, confidence: 42, status: "Blocked" },
];

export default function DesignSystemPage() {
  return <AppShell current="Design System"><header className="page-header"><div><p className="eyebrow">Internal reference · v0.2</p><h1 className="page-title">ExecLink Design System</h1><p className="page-description">A precise blue, white, and cool-neutral interface language for trusted infrastructure project controls. This page uses demonstration data only.</p></div></header>

  <section className="section"><SectionHeader title="Foundations" description="Core color, type, spacing, and surface decisions." meta="4 / 8px rhythm" /><div className="grid-2"><Surface className="surface-pad"><p className="eyebrow">Brand & interface</p><div className="swatch-grid">{brandColors.map(([name, value]) => <div className="swatch" key={name}><div className="swatch-color" style={{background: value}} /><div className="swatch-copy"><span className="swatch-name">{name}</span><span className="swatch-value">{value}</span></div></div>)}</div><p className="eyebrow" style={{marginTop: 22}}>Semantic only</p><div className="swatch-grid">{semanticColors.map(([name, value]) => <div className="swatch" key={name}><div className="swatch-color" style={{background: value}} /><div className="swatch-copy"><span className="swatch-name">{name}</span><span className="swatch-value">{value}</span></div></div>)}</div></Surface><Surface className="surface-pad"><p className="eyebrow">Typography</p><div className="type-sample"><span className="type-label">Page title · 27</span><span className="type-page">Execution Command Center</span></div><div className="type-sample"><span className="type-label">Section · 17</span><span className="type-section">Verification health</span></div><div className="type-sample"><span className="type-label">Body · 14</span><span className="type-body">Verified execution updates inform trusted progress.</span></div><div className="type-sample"><span className="type-label">Table · 13</span><span className="type-table">P-110 erection and alignment</span></div><div className="type-sample"><span className="type-label">Metadata · 12</span><span className="type-meta">Updated 4 minutes ago</span></div></Surface></div><div className="grid-3" style={{marginTop: 14}}><div className="surface-pad"><p className="eyebrow">Spacing scale</p><div className="spacing-row">{[4,8,12,16,24,32].map((size) => <div className="spacing-token" key={size}><div className="spacing-block" style={{height: size}} />{size}</div>)}</div></div><Surface className="surface-pad"><p className="eyebrow">Standard surface</p><p style={{margin: 0, color: "var(--text-secondary)"}}>Default working container with a quiet border and no shadow.</p></Surface><Surface variant="elevated" className="surface-pad"><p className="eyebrow">Elevated detail</p><p style={{margin: 0, color: "var(--text-secondary)"}}>Reserved elevation for contextual overlays and active detail.</p></Surface></div></section>

  <section className="section"><SectionHeader title="Panel Geometry" description="A deliberate hierarchy from workspace composition to control." /><MajorPanel><PanelHeader eyebrow="Surface hierarchy" title="Execution intelligence workspace" meta="Data Date · 26 Sep" /><div className="major-panel-body"><div className="grid-2"><div><p className="section-copy" style={{marginTop: 0, marginBottom: 14}}>The outer panel owns a complete user job. Smaller modules organize related evidence without becoming a field of disconnected cards.</p><div className="geometry-demo"><div className="geometry-shape geometry-major">Major panel · 18</div><div className="geometry-shape geometry-standard">Standard · 14</div><div className="geometry-shape geometry-compact">Module · 10</div><div className="geometry-shape geometry-control">Control · 8</div><div className="geometry-shape geometry-pill">Pill</div></div></div><div className="grid-2"><InsetModule><div className="module-heading"><span className="module-title">Inset module</span><span className="section-meta">Neutral</span></div><p style={{margin: 0, color: "var(--text-secondary)", fontSize: 12}}>Quiet technical grouping for supporting project information.</p></InsetModule><InsetModule focused><div className="module-heading"><span className="module-title">Focused module</span><ConfidenceBadge value={96} /></div><p style={{margin: 0, color: "var(--text-secondary)", fontSize: 12}}>Blue border communicates active intelligence or selection.</p></InsetModule></div></div></div></MajorPanel></section>

  <section className="section"><SectionHeader title="Panel Headers" description="Compact headers keep category, state, metadata, and actions aligned." /><div className="grid-2"><MajorPanel><PanelHeader title="Physical Progress" meta="Data Date · 26 Sep" /><div className="major-panel-body"><p style={{margin: 0, color: "var(--text-secondary)"}}>Standard title with right-aligned operational metadata.</p></div></MajorPanel><MajorPanel><PanelHeader eyebrow="Matching" title="Recommendation analysis" badge={<span className="badge blue">Intelligence</span>} action={<Button variant="ghost">Inspect <ArrowUpRight size={13} /></Button>} /><div className="major-panel-body"><p style={{margin: 0, color: "var(--text-secondary)"}}>Category, compact state badge, and a contextual action.</p></div></MajorPanel></div></section>

  <section className="section"><SectionHeader title="Actions & Inputs" description="A compact hierarchy for operational work." /><Surface className="surface-pad"><div className="grid-2"><div><p className="eyebrow">Actions</p><div className="stack"><Button variant="primary">Primary action</Button><Button>Secondary</Button><Button variant="ghost">Ghost</Button><Button variant="destructive">Destructive</Button></div></div><div><p className="eyebrow">Inputs</p><div className="grid-2"><label className="field"><span className="field-label">Activity ID</span><span className="input-wrap"><input placeholder="e.g. ACT-P110" /></span></label><div className="field"><span className="field-label">Project search</span><SearchInput placeholder="Search activity, tag, or WBS" /></div></div></div></div></Surface></section>

  <section className="section"><SectionHeader title="Status Language" description="Meaning is reinforced with text, tone, and a consistent marker." /><Surface className="surface-pad"><div className="stack">{statuses.map((status) => <StatusBadge key={status}>{status}</StatusBadge>)}</div><div style={{height: 20}} /><div className="grid-2"><div><p className="eyebrow">Confidence</p><div className="stack"><ConfidenceBadge value={96} /><ConfidenceBadge value={78} /><ConfidenceBadge value={42} /></div></div><div><p className="eyebrow">Disciplines</p><div className="stack">{disciplines.map((discipline) => <DisciplineBadge key={discipline}>{discipline}</DisciplineBadge>)}</div></div></div></Surface></section>

  <section className="section"><SectionHeader title="Metric Group" description="Four related measures contained by one substantial workspace panel." /><MajorPanel><PanelHeader title="Execution control summary" meta="Updated 4 min ago" /><div className="metric-group"><div className="metric"><div className="metric-label">VERIFIED ACTUAL</div><div className="metric-value">68.4%</div><div className="metric-detail">Through 26 Sep data date</div></div><div className="metric"><div className="metric-label">REVIEW BACKLOG</div><div className="metric-value">12</div><div className="metric-detail">3 require priority review</div></div><div className="metric"><div className="metric-label">SYSTEM STATE</div><div className="metric-value">Synced</div><div className="metric-detail">Last refresh 4 minutes ago</div></div><div className="metric"><div className="metric-label">HIGH CONFIDENCE</div><div className="metric-value">96%</div><div className="metric-detail">Top match proposal</div></div></div></MajorPanel></section>

  <section className="section"><SectionHeader title="Focused Intelligence Module" description="A reusable technical treatment for selected recommendations and explainable scoring." /><MajorPanel><PanelHeader eyebrow="Match intelligence" title="Recommended schedule activity" badge={<span className="badge blue"><Info size={11} />Selected</span>} meta="ACT-P110" /><div className="major-panel-body"><InsetModule focused><div className="module-heading"><span className="module-title">Match confidence</span><span className="module-value">96%</span></div><div className="signal-list"><div className="signal-row"><span>Asset / Tag</span><span className="signal-track"><span className="signal-fill" style={{width: "100%"}} /></span><span className="signal-number">30%</span></div><div className="signal-row"><span>Discipline</span><span className="signal-track"><span className="signal-fill" style={{width: "82%"}} /></span><span className="signal-number">20%</span></div><div className="signal-row"><span>Location</span><span className="signal-track"><span className="signal-fill" style={{width: "74%"}} /></span><span className="signal-number">18%</span></div><div className="signal-row"><span>Temporal fit</span><span className="signal-track"><span className="signal-fill" style={{width: "66%"}} /></span><span className="signal-number">14%</span></div></div></InsetModule></div></MajorPanel></section>

  <section className="section"><SectionHeader title="Data & Filters" description="Filters and dense operational data behave as one substantial workspace." meta="4 demonstration activities" /><Surface className="table-workspace"><div className="filter-bar"><SearchInput label="Filter activities" placeholder="Filter activities" /><button className="filter-chip"><Filter size={13} />Discipline<ChevronDown size={12} /></button><button className="filter-chip">Status<ChevronDown size={12} /></button><button className="filter-chip">Confidence<ChevronDown size={12} /></button><span className="filter-spacer" /><Button variant="ghost">Clear filters</Button></div><div className="table-scroll"><table className="data-table"><thead><tr><th>Activity ID</th><th>Activity</th><th>Discipline</th><th>Progress</th><th>Confidence</th><th>Status</th></tr></thead><tbody>{activities.map((item, index) => <tr key={item.id} className={index === 1 ? "selected" : undefined}><td><span className="activity-id">{item.id}</span></td><td><span className="activity-name">{item.name}</span></td><td><DisciplineBadge>{item.discipline}</DisciplineBadge></td><td className="progress-cell"><span style={{display: "flex", alignItems: "center"}}><span className="progress-track"><span className="progress-fill" style={{width: `${item.progress}%`}} /></span><span className="progress-label">{item.progress}%</span></span></td><td><ConfidenceBadge value={item.confidence} /></td><td><StatusBadge>{item.status}</StatusBadge></td></tr>)}</tbody></table></div></Surface></section>

  <section className="section"><SectionHeader title="Detail Interaction" description="Context stays visible through focused drawers, modal decisions, and lightweight popovers." /><Surface className="surface-pad"><div className="demo-controls"><DrawerDemo /><ModalDemo /><PopoverDemo /></div></Surface></section>

  <section className="section"><SectionHeader title="System States" description="Purposeful loading, empty, and recoverable error treatment." /><div className="grid-3"><SkeletonState /><EmptyState /><ErrorState /></div></section>
  </AppShell>;
}
